server:
  port:
    8080
spring:
  application:
    name: 'public-cloud-exam-2024'
  datasource:
    url: 'jdbc:mysql://database-2.cxsisye60l2u.ap-northeast-2.rds.amazonaws.com:3306/exam?serverTimezone=Asia/Seoul&useLegacyDatetimeCode=false&zeroDateTimeBehavior=convertToNull&cacheDefaultTimezone=false'
    username: ${RDS_USER}
    password: ${RDS_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect