on:
  push:
    branches: ['main']

jobs:
  build-docker-image:
    runs-on: 'ubuntu-22.04'
    steps:
      - uses: 'actions/checkout@v4'

      - name: 'Set Up JDK 17'
        uses: 'actions/setup-java@v4'
        with:
          distribution: 'corretto'
          java-version: 17

      - name: 'Setup Gradle'
        uses: 'gradle/actions/setup-gradle@v4'

      - name: 'Build with Gradle'
        env:
          RDS_USER: ${{ secrets.RDS_USER }}
          RDS_PASSWORD: ${{ secrets.RDS_PASSWORD }}
        run: |
          chmod +x ./gradlew
          ./gradlew clean build

      - name: 'Login to DockerHub'
        uses: 'docker/login-action@v1'
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: 'DockerHub Upload'
        id: dockerhub-image
        env:
          DOCKER_HUB_USERNAME: ${{ secrets.DOCKER_HUB_USERNAME}}
          DOCKER_HUB_REPOSITORY: '2024-public-cloud-exam'
          IMAGE_TAG: ${{ github.sha }}
        run: |
          docker buildx build -t $DOCKER_HUB_REPOSITORY .
          docker tag $DOCKER_HUB_REPOSITORY:latest $DOCKER_HUB_USERNAME/$DOCKER_HUB_REPOSITORY:$IMAGE_TAG
          docker push $DOCKER_HUB_USERNAME/$DOCKER_HUB_REPOSITORY:$IMAGE_TAG
          echo "image=$DOCKER_HUB_USERNAME/$DOCKER_HUB_REPOSITORY:$IMAGE_TAG" >> $GITHUB_OUTPUT